# - name: "print the conditions"
#   hosts: local
#   connection: local
#   vars:
#     number: 5
#   tasks:
#     - name: number is lessthan 5
#       ansible.builtin.debug:
#         msg: "the num is: {{number}}"
#       when: number < 10



- name: "gather the facts"
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: "install nginx if redhat"
      ansible.builtin.dnf:
      name: nginx
      state: present
      when: ansible_os_family= "redhat"
            