# - name: loops concepts
#   hosts: local
#   connection: local
#   become: yes
#   tasks:
#     - name: print names
#       ansible.builtin.debug:
#         msg: "hello friends: {{ item }}"
#       loop:
#         - ram
#         - rahim
#         - sita 
#         - gita




- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: istall packages
      ansible.builtin.package:
        msg: "packages are: {{ item }}"
      loop:
        - nginx
        - mysql
        - zip
