- name: cart setup
  hosts: cart
  become: yes

  tasks:

    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create system cart
      ansible.builtin.user:
        name: roboshop
        comment: roboshop system cart
        system: true
        shell: /sbin/nologin
        home: /app

    - name: delete app directory before create
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app


    - name: delete cart file before create
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent


    - name: download application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: unzip the application
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: download dependencies
      community.general.npm:
        path: /app

    - name: copy service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service


    # - name: start and enable service
    #   ansible.builtin.service:
    #     name: cart
    #     state: started
    #     enable: yes
        # daemon-reload: true


    - name: start ans enable cart service
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes

