- name: catalogue setup
  hosts: catalogue
  become: yes

  tasks:

    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
     
    - name: create system user
      ansible.builtin.user:
        name: roboshop
        component: roboshop system user
        system: true
        shell: /sbin/nologin
        home: /app

    - name: delete app directory before create
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app


    - name: delete catalogue file before create
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent


    - name: download application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: unzip the application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: download dependencies
      community.general.npm:
        path: /app

    - name: copy service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy service file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    - name: connect mongodb to catalogue
      ansible.builtin.command: INDEX=$(mongosh mongodb.daws86s.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')")
      register: catalogue_output

    - name: load products in mongodb
      ansible.builtin.shell: mongosh --host mongodb.lakshmimopidevi.fun </app/db/master-data.js
      when: catalogue_output.stdout | int < 0

    - name: start ans enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes


