- name: mongodb setup 
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongorepo file 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install MongoDB
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'


  - name: Start & Enable MongoDB Service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  



  