- name: setup rabbitmq
  hosts: rabbitmq
  become: true

  tasks: 
    - name: copy rabbitmq file
      ansible.builtin.copy:
        src:  rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install RabbitMQ
      ansible.builtin.package:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ Service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: create roboshop user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present



