- name: setup shipping server
  hosts: shipping
  become: true

  tasks:
    
    - name: install maven
      ansible.builtin.dnf:
        name: "{{item}}"
        state: present

      loop:
        - maven
        - mysql

    - name: install mysql
      ansible.builtin.pip:
        executable: pip3.9
        name: "{{item}}"

      loop:
        - cryptograpy
        - PyMySql
    
  

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        comment: roboshop system user
        system: true
        shell: /sbin/nologin
        home: /app    


    - name: delete app directory before create
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        


    - name: delete shipping file before create
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent


    - name: download application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unzip the application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: move jar file
      ansible.builtin.shell: mv target/*.jar shipping.jar
      args:
        chdir: /app

    - name: copy service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon reload
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: start and enable shipping service
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes

    - name: import shipping data into mysql
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: mysql.lakshmimopidevi.fun
        login_user: root
        login_password: RoboShop@1
        target: "{{item}}"
      loop:
         - /app/db/schema.sql
         - /app/db/app-user.sql
         - /app/db/master-data.sql

    - name: start ans enable cart service
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes










